### General project setup
general:
  gitSshKeyCredentialsId: 'githubCredentialsId'
  productiveBranch: 'main'
  buildTool: 'mta'

### Step-specific configuration
steps:
  uiVeri5ExecuteTests:
    runOptions: ["--seleniumAddress=http://selenium:4444/wd/hub", "./app/admin/webapp/test/uiveri5/conf.js"]

  cloudFoundryDeploy:
    cloudFoundry:
      org: '54b1103atrial'
      space: 'dev2'
      credentialsId: 'CF_CREDENTIALSID'
      apiEndpoint: 'https://api.cf.ap21.hana.ondemand.com'

### Stage-specific configuration
stages:
  'Central Build':
    buildExecute : true

  'Confirm':
    manualConfirmation: false

  'Release':
    cloudFoundryDeploy: false
